FROM jonasbn/ebirah:0.4.0

LABEL "com.github.actions.name"="CI Action"
LABEL "com.github.actions.description"="Continuous Integration test of files in repository"
LABEL "com.github.actions.icon"="mic"
LABEL "com.github.actions.color"="purple"

LABEL "repository"="https://github.com/jonasbn/perl-date-holidays-super"

ENTRYPOINT ["/entrypoint.sh"]
